DjangoUeditor3-master/DUSite/urls.py
#coding:utf-8
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
import settings
from django.contrib import admin
from TestApp.views import  TestUEditorModel,ajaxcmd,TestUEditor

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DUSite.views.home', name='home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^test/$',TestUEditorModel),
    url(r'^test2/$',TestUEditor),
    url(r'^ajaxcmd/$',ajaxcmd)

)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
        url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
        url(r'^(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
    )

HigreenWeb02/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('articles.urls')),
# url(r'^article/', include('articles.urls')),
    url(r'ueditor/', include('DjangoUeditor.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^price/', include('price.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.conf.urls import url, include
from . import views
from articles.views import ListView, MediaListView, BianminListView, DangqunListView, GonggaoListView, JiageView, ShucaiView

app_name = 'article'

urlpatterns = [
    url(r'^$', views.index, name='article_index'),
    url(r'^article/price', views.price, name='article_price'),
    # url(r'^(?P<article_id>[0-9]+)/$', views.detail, name='article_detail'),
    # url(r'^list/detail/(?P<article_id>[0-9]+)/$', views.detail, name='article_detail'),
    url(r'^qiye$', views.qiye, name='article_qiye'),
    url(r'^xinwen$', views.xinwen, name='article_xinwen'),
    url(r'^xinwen2$', views.xinwen2, name='article_xinwen2'),
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'), # 新闻列表页
    url(r'^(?P<artical_category>\w+)/detail/(?P<entry_id>\d+)$', views.ListDetail, name='detail'), # 新闻详情页
    # url(r'^medialist/(?P<page>\d+)$', MediaListView.as_view(), name='medialist'), # 媒体播报列表页
    url(r'^bianminlist/(?P<type_id>\d+)/(?P<page>\d+)$', BianminListView.as_view(), name='bianminlist'),
    url(r'^bianminlist/jiage$', JiageView.as_view(), name='jiagelist'),
    url(r'^bianminlist/shucai$', ShucaiView.as_view(), name='shucailist'),
    url(r'^dangqunlist/(?P<type_id>\d+)/(?P<page>\d+)$', DangqunListView.as_view(), name='dangqunlist'),
    url(r'^gonggaolist/(?P<type_id>\d+)/(?P<page>\d+)$', GonggaoListView.as_view(), name='gonggaolist'),
    url(r'^bianmin$', views.bianmin, name='article_bianmin'),
    url(r'^yuanqu$', views.yuanqu, name='article_yuanqu'),
    url(r'^dangqun$', views.dangqun, name='article_dangqun'),
    url(r'^gonggao$', views.gonggao, name='article_gonggao'),
    url(r'^fupin$', views.fupin, name='article_fupin'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # url(r'^category/(?P<category_id>[0-9]+)/$', views.category, name='article_category'),
    url(r'^yuanqu/gouwu$', views.gouwu, name='article_gouwu'),
    url(r'^yuanqu/yewu$', views.yewu, name='article_yewu'),
    url(r'^yuanqu/cheka$', views.cheka, name='article_cheka'),
    url(r'^yuanqu/jiesuan$', views.jiesuan, name='article_jiesuan'),
    url(r'^yuanqu/kefu$', views.kefu, name='article_kefu'),
    url(r'^jiage$', views.jiage, name='article_jiage'),
]

price/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'price'

urlpatterns = [
    url(r'^price$', views.price, name='article_price'),
    url(r'^price02$', views.price02, name='article_price02'),
    url(r'^price03$', views.price03, name='article_price03'),
]

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# from ckeditor.fields import RichTextField
# from ckeditor_uploader.fields import RichTextUploadingField
from DjangoUeditor.models import UEditorField

# Create your models here.


class Category(models.Model):

    name = models.CharField(max_length=128, verbose_name='文章分类')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "文章分类"
        verbose_name_plural = '文章分类'


# class Tag(models.Model):
#
#     name = models.CharField(max_length=128, verbose_name='文章标签')
#
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         verbose_name = "文章标签"
#         verbose_name_plural = '文章标签'


class Entry(models.Model):

    title = models.CharField(max_length=128, verbose_name='文章标题')

    author = models.ForeignKey(User, verbose_name='文章作者', on_delete=models.CASCADE)

    category = models.ManyToManyField('Category', verbose_name='文章分类')

    abstract = models.TextField(max_length=256, blank=True, null=True, verbose_name='文章摘要')

    # img = models.ImageField(upload_to='blog_images', null=True, blank=True, verbose_name='文章配图')

    img = models.ImageField(null=True, blank=True, verbose_name='文章配图')

    visiting = models.PositiveIntegerField(default=0, verbose_name='文章访问量')

    # body = RichTextUploadingField(verbose_name='文章正文')

    body = UEditorField(verbose_name='文章正文', width=800)

    # tags = models.ManyToManyField('Tag', verbose_name='文章+标签')

    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    modified_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:article_detail', kwargs={'article_id': self.id})  # http://127.0.0.1/article/3

    def increase_visiting(self):
        self.visiting += 1
        self.save(update_fields=['visiting'])

    class Meta:
        ordering = ['-created_time']
        verbose_name = "文章"
        verbose_name_plural = "文章"


class Media(models.Model):

    title = models.CharField(max_length=128, verbose_name='标题')

    category = models.ManyToManyField('Category', verbose_name='文章分类')

    origin = models.CharField(max_length=24, verbose_name='发布方', null=False)

    abstract = models.TextField(max_length=256, blank=True, null=True, verbose_name='摘要')

    img = models.ImageField(upload_to='blog_images', null=True, blank=True, verbose_name='配图')

    visiting = models.PositiveIntegerField(default=0, verbose_name='文章访问量')

    get_absolute_url = models.CharField(max_length=512, verbose_name='来源地址')

    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __str__(self):
        return self.title

    def increase_visiting(self):
        self.visiting += 1
        self.save(update_fields=['visiting'])


    class Meta:
        verbose_name = "媒体播报"
        verbose_name_plural = '媒体播报'


class Price(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=64, null=False, verbose_name='品名')
    price = models.CharField(max_length=8, null=False, verbose_name='价格')
    unit = models.CharField(max_length=4, null=False, verbose_name='单位')
    create_time = models.DateField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        # 指定表名
        db_table = 'news_price'

        verbose_name = '价格表'
        verbose_name_plural = verbose_name

articles/views.py
from django.shortcuts import render
from django.views.generic import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.db import connection
from django.http import JsonResponse

from . import models

# Create your views here.


def index(request):
    print(request.path)
    return render(request, 'article/index4.html', locals())


def price(request):
    print(111111111111111111111111111111111111111111)
    # 获取游标对象
    cursor = connection.cursor()
    # 拿到游标对象后执行sql语句
    cursor.execute("select * from news_price")
    # 获取所有的数据
    rows = cursor.fetchall()
    # 遍历查询到的数据

    return JsonResponse(rows, safe=False)


def detail(request, article_id):
    article = models.Entry.objects.get(id=article_id)
    category = models.Category.objects.filter(id=article.id)
    article.increase_visiting()
    print(article.category)
    print(category)
    print(article.id)
    return render(request, 'article/信息详情.html', locals())


def ListDetail(request, artical_category, entry_id):
    article = models.Entry.objects.get(id=entry_id)
    category = models.Category.objects.filter(id=article.id)
    article.increase_visiting()
    print(article.category)
    print(category)
    print(article.id)
    return render(request, 'article/信息详情.html', locals())


def qiye(request):
    print(request.path)
    return render(request, 'article/企业概况3练习.html', locals())


def xinwen(request):
    entries = models.Entry.objects.all()
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'article/新闻中心2.html', locals())


def xinwen2(request):
    # 园区动态文章列表
    c01 = models.Category.objects.get(id=1)
    entries_01 = models.Entry.objects.filter(category=c01)
    page_01 = request.GET.get('page', 1)
    entry_list_01, paginator_01 = make_paginator(entries_01, page_01)
    page_data_01 = pagination_data(paginator_01, page_01)
    # 媒体播报文章列表
    c02 = models.Category.objects.get(id=2)
    entries_02 = models.Entry.objects.filter(category=c02)
    page_02 = request.GET.get('page', 1)
    entry_list_02, paginator_02 = make_paginator(entries_02, page_02)
    page_data_02 = pagination_data(paginator_02, page_02)
    return render(request, 'article/新闻中心2.html', locals())


# def category(request, category_id):
#     c = models.Category.objects.get(id=category_id)
#     # c = get_object_or_404(models.Category, id=category_id)
#     entries = models.Entry.objects.filter(category=c)
#     page = request.GET.get('page', 1)
#     entry_list, paginator = make_paginator(entries, page)
#     page_data = pagination_data(paginator, page)
#     return render(request, 'article/新闻中心.html', locals())


def bianmin(request):
    entries = models.Entry.objects.all()
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'article/便民信息.html', locals())

def jiage(request):
    return render(request, 'article/价格分页.html', locals())

def yuanqu(request):
    return render(request, 'article/园区指南.html', locals())

def gouwu(request):
    return render(request, 'article/购物指南.html', locals())

def yewu(request):
    return render(request, 'article/业务办理.html', locals())

def cheka(request):
    return render(request, 'article/车卡业务.html', locals())

def jiesuan(request):
    return render(request, 'article/结算业务.html', locals())

def kefu(request):
    return render(request, 'article/客服业务.html', locals())

def fupin(request):
    return render(request, 'article/扶贫中心.html', locals())


def dangqun(request):
    entries = models.Entry.objects.all()
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'article/党群建设.html', locals())


def gonggao(request):
    entries = models.Entry.objects.all()
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'article/公告栏.html', locals())


def make_paginator(objects, page, num=5):
    paginator = Paginator(objects, num)
    try:
        object_list = paginator.page(page)
    except PageNotAnInteger:
        object_list = paginator.page(1)
    except EmptyPage:
        object_list = paginator.page(paginator.num_pages)
    return object_list, paginator


def pagination_data(paginator, page):
    """
    用于自定义展示分页页码的方法
    :param paginator: Paginator类的对象
    :param page: 当前请求的页码
    :return: 一个包含所有页码和符号的字典
    """
    if paginator.num_pages == 1:
        # 如果无法分页，也就是只有1页不到的内容，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
        return {}
    # 当前页左边连续的页码号，初始值为空
    left = []

    # 当前页右边连续的页码号，初始值为空
    right = []

    # 标示第 1 页页码后是否需要显示省略号
    left_has_more = False

    # 标示最后一页页码前是否需要显示省略号
    right_has_more = False

    # 标示是否需要显示第 1 页的页码号。
    # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
    # 其它情况下第一页的页码是始终需要显示的。
    # 初始值为 False
    first = False

    # 标示是否需要显示最后一页的页码号。
    # 需要此指示变量的理由和上面相同。
    last = False

    # 获得用户当前请求的页码号
    try:
        page_number = int(page)
    except ValueError:
        page_number = 1
    except:
        page_number = 1

    # 获得分页后的总页数
    total_pages = paginator.num_pages

    # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
    page_range = paginator.page_range

    if page_number == 1:
        # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
        # 此时只要获取当前页右边的连续页码号，
        # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
        # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
        right = page_range[page_number:page_number + 4]

        # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
        # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
        if right[-1] < total_pages - 1:
            right_has_more = True

        # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
        # 所以需要显示最后一页的页码号，通过 last 来指示
        if right[-1] < total_pages:
            last = True

    elif page_number == total_pages:
        # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
        # 此时只要获取当前页左边的连续页码号。
        # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
        # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

        # 如果最左边的页码号比第 2 页页码号还大，
        # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
        if left[0] > 2:
            left_has_more = True

        # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
        # 所以需要显示第一页的页码号，通过 first 来指示
        if left[0] > 1:
            first = True
    else:
        # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
        # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
        right = page_range[page_number:page_number + 2]

        # 是否需要显示最后一页和最后一页前的省略号
        if right[-1] < total_pages - 1:
            right_has_more = True
        if right[-1] < total_pages:
            last = True

        # 是否需要显示第 1 页和第 1 页后的省略号
        if left[0] > 2:
            left_has_more = True
        if left[0] > 1:
            first = True

    data = {
        'left': left,
        'right': right,
        'left_has_more': left_has_more,
        'right_has_more': right_has_more,
        'first': first,
        'last': last,
    }
    return data


def category(request, category_id):
    c = models.Category.objects.get(id=category_id)
    # c = get_object_or_404(models.Category, id=category_id)
    entries = models.Entry.objects.filter(category=c)
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'article/新闻中心.html', locals())


# 种类id 页码 排序方式
# restful api -> 请求一种资源
# /list?type_id=种类id&page=页码&sort=排序方式
# /list/种类id/页码/排序方式
# /list/种类id/页码?sort=排序方式
class ListView(View):
    '''列表页'''
    def get(self, request, type_id, page):
        '''显示列表页'''
        # 获取种类信息
        # try:
        #     type = GoodsType.objects.get(id=type_id)
        # except GoodsType.DoesNotExist:
        #     # 种类不存在
        #     return redirect(reverse('goods:index'))
        #
        # # 获取商品的分类信息
        # types = GoodsType.objects.all()
        if int(type_id)==1:
            category = models.Category.objects.get(id=type_id)
            entry_list = models.Entry.objects.filter(category=category)
        elif int(type_id)==2:
            category = models.Category.objects.get(id=type_id)
            entry_list = models.Media.objects.all()
            print(123)

        # 获取排序的方式 # 获取分类商品的信息
        # sort=default 按照默认id排序
        # sort=price 按照商品价格排序
        # sort=hot 按照商品销量排序
        sort = request.GET.get('sort')
        if not sort:
            sort = 'default'
        print(sort)
        #
        # if sort == 'price':
        #     skus = GoodsSKU.objects.filter(type=type).order_by('price')
        # elif sort == 'hot':
        #     skus = GoodsSKU.objects.filter(type=type).order_by('-sales')
        # else:
        #     sort = 'default'
        #     skus = GoodsSKU.objects.filter(type=type).order_by('-id')

        # 对数据进行分页
        paginator = Paginator(entry_list, 1)

        # 获取第page页的内容
        try:
            page = int(page)
        except Exception as e:
            page = 1

        if page > paginator.num_pages:
            page = 1

        # 获取第page页的Page实例对象
        # skus_page = paginator.page(page)
        entry_list_page = paginator.page(page)


        # 1.总页数小于5页，页面上显示所有页码
        # 2.如果当前页是前3页，显示1-5页
        # 3.如果当前页是后3页，显示后5页
        # 4.其他情况，显示当前页的前2页，当前页，当前页的后2页
        num_pages = paginator.num_pages
        if num_pages < 5:
            pages = range(1, num_pages+1)
        elif page <= 3:
            pages = range(1, 6)

articles/templates/article/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail</title>
</head>
<body>
detail
{{ article.category }}
{{ article.abstract }}
{{ article.title }}
<img src="{{ article.img.url }}">
{{ category }}
</body>
</html>

articles/templates/article/水果价格.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>HIGREEN海吉星</title>
    <link href="{% static 'article/css/reset.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'article/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'article/css/bootstrap-maizi4便民信息.css' %}" rel="stylesheet">
    <link href="{% static 'article/css/animate.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'article/css/bootstrap-table.css' %}" />
</head>
<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand"><img src="{% static 'article/images/LOGO3.PNG' %}" class="img-responsive" alt="logo"/></a>

            <div class="weixin">
                <img src="{% static 'article/images/weixin.PNG' %}" class="img-responsive weixin2" alt="logo"/>
                <div class="erweima">
                    <img src="{% static 'article/images/服务平台.png' %}">
{#                    <img src="{% static 'article/images/扶贫小程序码.PNG' %}">#}
                </div>
            </div>

        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">

                <li {% if request.path == '/'%}class="navactive" {% endif %} ><a href="/">首页</a></li>
                <li {% if request.path == '/qiye'%}class="navactive" {% endif %} ><a href="/qiye">企业概况</a></li>
                <li {% if request.path|slice:':5' == '/list'%}class="navactive" {% endif %}><a href="/list/1/1">新闻中心</a></li>
                <li {% if request.path|slice:':12' == '/bianminlist'%}class="navactive" {% endif %}><a href="/bianminlist/3/1">便民信息</a></li>
                <li {% if request.path|slice:':7' == '/yuanqu'%}class="navactive" {% endif %}><a href="/yuanqu">园区指南</a></li>
                <li {% if request.path|slice:':12' == '/dangqunlist'%}class="navactive" {% endif %}><a href="/dangqunlist/6/1">党群建设</a></li>
                <li {% if request.path|slice:':12' == '/gonggaolist'%}class="navactive" {% endif %}><a href="/gonggaolist/9/1">公告栏</a></li>
                <li {% if request.path|slice:':6' == '/fupin'%}class="navactive" {% endif %}><a href="/fupin">扶贫中心</a></li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->

<!--home-->
<section id="home">
{#    <img src="images/aboutus.jpg" class="img-responsive" alt="企业概况图片"/>#}
    <img src="{% static 'article/images/便民信息11.jpg' %}" class="img-responsive" alt="企业概况图片"/>
</section>
<!--home-->


<!--bbs4-->
<section id="bbs4">
    <div class="container">
        <div class="row wow fadeInUp" data-wow-duration="0.5s">
            <div class="col-md-2 col-xs-2">
                <div class="outer ">
                    <div class="inner ">
                        <span class="left">便民信息</span>
                    </div>

                    <!--</div>-->
                    <div class="list-group list2">
                        <a href="{% url 'article:bianminlist' 3 1 %}" {% if sort == 'default' %}class="active"{% endif %}>政策法规<br></a>
				        <a href="{% url 'article:bianminlist' 4 1 %}?sort=shian" {% if sort == 'shian' %}class="active"{% endif %}>食安與情<br></a>
                        <a href="{% url 'article:bianminlist' 5 1 %}?sort=shipin" {% if sort == 'shipin' %}class="active"{% endif %}>食品知识<br></a>
                        <a href="{% url 'article:jiagelist' %}?sort=shuiguo" {% if sort == 'shuiguo' %}class="active"{% endif %} id="shuiguo">水果价格</a>
                        <a href="{% url 'article:shucailist' %}?sort=shucai" {% if sort == 'shucai' %}class="active"{% endif %} id="shucai">蔬菜价格</a>
                    </div>

                </div>
            </div>
            <!--政策法规-->
            <div class="col-md-10 col-xs-10 bbsRight selected">
                <div class="outer">
                    <div class="col-md-1"></div>
                    <div class="col-md-11">
                        <div class="inner">
                            {% if sort == 'shuiguo' %}
                                <span class="right">水果价格</span>
                                {% elif sort == 'shucai' %}
                                    <span class="right">蔬菜价格</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-11">
                        <div class="conter_con noactive">
                            <div id="reportTableDiv" >
                                <table id="reportTable"></table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!--bbs4-->


<!--footer-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <p>
                    客服中心：4008000061转8    公司传真：0755-89695958
                </p>
                <p>
                    地址：深圳市龙岗区平湖白坭坑社区丹农路1号
                </p>
                <br>
                <p>
                    © 深圳海吉星, 2016. All rights reserved    粤ICP备14057873号-4    粤公网安备 44030702000610号
                </p>
            </div>
        </div>
    </div>
</footer>
<!--footer-->


{#<script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>#}
<script src="{% static 'article/js/jquery-1.12.4.js' %}"></script>
<script src="{% static 'article/js/bootstrap.min.js' %}"></script>
<script src="{% static 'article/js/jquery.singlePageNav.min.js' %}"></script>
<script src="{% static 'article/js/wow.min.js' %}"></script>
<script src="{% static 'article/js/bootstrap-table.js' %}"></script>
<script src="{% static 'article/js/bootstrap-table-export.js' %}"></script>
<script src="{% static 'article/js/jquery.base64.js' %}"></script>
<script src="{% static 'article/js/tableExport.js' %}"></script>
<script>
    	$(function () {

	    var datas = [];
	    $.ajax({
            type: "get",
            url: "/price/price",
            // timeout 可以设置超时时间, 表示如果 2s 内, 响应还没有回来, 就认为超时
            timeout: 20000,

            success: function (info) {
{#                console.log(info)#}
                datas = info

                $('#reportTable').bootstrapTable({
                    method: 'get',
                    cache: false,
                    height: 700,
        {#			striped: true,#}
                    pagination: true,
                    pageSize: 20,
                    pageNumber:1,
                    pageList: [10, 20, 50, 100, 200, 500],
        {#			search: true,#}
        {#			showColumns: true,#}
        {#			showRefresh: false,#}
        {#			showExport: false,#}
                    exportTypes: ['csv','txt','xml'],
        {#			search: true,#}
        {#			clickToSelect: false,#}
        {#			clickToSelect: true,#}
                    sidePagination: "client",           //分页方式：client客户端分页，server服务端分页（*）
                    columns:
                    [
                        {field:"name",title:"品种",align:"center",sortable:"true"},
                        {field:"price",title:"价格(元\\kg)",align:"center",sortable:"true"},
                        {field:"area",title:"产地",align:"center",sortable:"true"},
                        {field:"day",title:"日期",align:"center",sortable:"true"},
                    ],
                    data:datas,
                });
            }
        })
            console.log(datas)

	});
</script>
</body>
</html>